### ISSUE TITLE
run-warrior2: command not found

### ISSUE THREAD

**Issue by reinierkors** [ArchiveTeam/warrior-dockerfile#31]
Using clean docker compose setup:

```
  archiveteam:
    container_name: archiveteam
    restart: unless-stopped
    image: archiveteam/warrior-dockerfile
    volumes:
      - /media/archiveteam:/data/data
    ports:
      - "8001:8001"
    environment:
      - "DOWNLOADER=downloader"
      - "SELECTED_PROJECT=auto"
      - "CONCURRENT_ITEMS=6"
```

/var/log/warrior.log
> ./warrior-runner.sh: line 17: run-warrior2: command not found
> ./warrior-runner.sh: line 17: run-warrior2: command not found
> ./warrior-runner.sh: line 17: run-warrior2: command not found
> ./warrior-runner.sh: line 17: run-warrior2: command not found
> ./warrior-runner.sh: line 17: run-warrior2: command not found
> ./warrior-runner.sh: line 17: run-warrior2: command not found
