### ISSUE TITLE
Zombie wget-at and curl processes

### ISSUE THREAD

**Issue by cdzombak** [ArchiveTeam/warrior-dockerfile#87]
After running Warrior in Docker for a couple weeks, I noticed a large number (>1800) of zombie processes on my server.

These are `curl` and `wget-at` instances that I traced back to ArchiveTeam Warrior. A sample:

```
…
cdzombak  670782  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
cdzombak  671093  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
cdzombak  671957  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
cdzombak  672247  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
cdzombak  672484  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
cdzombak  672878  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
cdzombak  673095  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [wget-at] <defunct>
…
cdzombak  670960  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  674664  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  676110  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  677882  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  680172  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  683753  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  685059  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  686465  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  688020  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
cdzombak  689696  0.0  0.0      0     0 ?        Z    Jul30   0:00      \_ [curl] <defunct>
…
```

My `docker-compose` file:

```
---
services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archiveTeamWarrior
    hostname: archiveTeamWarrior
    ports:
      - "9050:8001"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    environment:
      - DOWNLOADER=<omitted>
      - SELECTED_PROJECT=auto
```

OS: Ubuntu 22.04.4 LTS
Docker: version 27.0.3, build 7d4bcd8
